server:
  port: 8201
spring:
  application:
    name: ribbon-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:123@localhost:8001/eureka/
service-url:
  user-service: http://user-service
