server:
  port: 8003
spring:
  application:
    name: eureka-cluster2-server
  security:
    user:
      name: admin
      password: 123
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://admin:123@localhost:8002/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true
    register-with-eureka: true
