server:
  port: 8083
spring:
  application:
    name: provider2-server
  datasource:
    url: jdbc:mysql://192.168.101.129:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  main:
    # bean 默认名称相同覆盖
    allow-bean-definition-overriding: true
  cloud:
    # nacos 注册中心配置
    nacos:
      discovery:
        server-addr: 192.168.101.134:8848
    # sentinel 服务治理
    sentinel:
      eager: true
      transport:
        dashboard: 192.168.101.134:8989
    # 事务
    alibaba:
      seata:
        tx-service-group: seata-test
    # mq 配置
    stream:
      rocketmq:
        binder:
          name-server: 192.168.101.134:9876
      #使用函数式绑定topic名称
      function:
        definition: test1
      #指定消费者的topic和group
      bindings:
        test1-in-0:
          destination: test1
          group: test1-group
          content-type: application/json
#dubbo 配置
dubbo:
  #提供服务类路径
  scan:
    base-packages: com.lqz.demo.service
  #dubbo 基础配置
  protocol:
    name: dubbo
    port: -1
    serialization: protostuff
    charset: UTF-8
  cloud:
    subscribed-services:

mybatis:
  mapper-locations:
  - classpath:mybatis-mapper/com/**/mapper/*.xml

mybatis-plus:
  type-aliases-package: io.seata.sample.entity

seata:
  enabled: true
  service:
    vgroup-mapping:
      seata-test: default
    grouplist:
      default: 192.168.101.134:8091
    disable-global-transaction: false