server:
  port: 8002
spring:
  application:
    name: eureka-cluster-server
  security:
    user:
      name: admin
      password: 123
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://admin:123@localhost:8003/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true
    register-with-eureka: true
