server:
  port: 8101
spring:
  application:
    name: eureka-client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:123@localhost:8001/eureka/,http://admin:123@localhost:8002/eureka/,http://admin:123@localhost:8003/eureka/
